esphome:
  name: peppertent
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

i2c:
  sda: 4
  scl: 5
  scan: True
  
sensor:
  - platform: bme280
    temperature:
      name: "Pepper Tent Temp"
      oversampling: 16x
    humidity:
      name: "Pepper Tent Humidity"
      filters:
        - offset: -1.4     
    address: 0x76
    update_interval: 30s
  - platform: bme280
    temperature:
      name: "Pepper Tent Temp 2"
      oversampling: 16x
    humidity:
      name: "Pepper Tent Humidity 2"
      filters:
        - offset: -9.6
    address: 0x77
    update_interval: 30s